version: '2.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=111111
      - POSTGRES_DB=fb-sync
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
  fb-sync:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test
    restart: always
    environment:
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER_NAME=root
      - DB_PASSWORD=111111
      - DB_DATABASE=fb-sync
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_TYPE=single
    ports:
      - '1000:1000'

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - '6379:6379'
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  postgres-volume:
    driver: local
  redis-data:
