version: '3'
services:
  fb-sync-cmt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fb-sync-cmt
    restart: always
    environment:
      - PORT=1000
      - DB_TYPE=mysql
      - DB_HOST=103.67.196.23
      - DB_PORT=3306
      - DB_USER_NAME=root
      - DB_PASSWORD=Thanhtho96@1111
      - DB_DATABASE=homstay
      - NODE_OPTIONS=--max-old-space-size=4096
      # redis
      - REDIS_HOST=103.67.196.23
      - REDIS_PORT=6379
      - REDIS_TYPE=single
    ports:
      - '1000:1000'
